#################################################
# Playbook: Initial Workstation Setup
#################################################
---
- hosts: linuxhost
  become: true
  vars_files:
    - vars/default.yml

  tasks:

# Install Packages
   - name: Update apt
     apt: update_cache=yes

   - name: Install required system packages
     apt: name={{ sys_packages }} state=latest

#  Process for install Microsoft Teams from the official repo: Key
    - name: Installing Key for Teams
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

 # Process for install Microsoft Teams from the official repo: Repo
    - name: Installing more packages
      apt_repository:
        repo: deb https://packages.microsoft.com/repos/ms-teams stable main
        state: present

#Process for install Microsoft Teams from the official repo: Installing finally
    - name: Installing teams finally!!!
      apt:
        name: teams
        update_cache: yes
